http:
  routers:
    jackett:
      rule: "Host(`jackett.tiamat.local`)"
      service: jackett
      entryPoints:
        - web

    deluge-fallback:
      rule: "Host(`deluge.tiamat.local`)"
      service: deluge-fallback
      entryPoints:
        - web

  services:
    jackett:
      loadBalancer:
        servers:
          - url: "http://192.168.12.211:9117"

    deluge-fallback:
      loadBalancer:
        servers:
          - url: "http://192.168.12.213:8112"
