# NexusOS Limine Boot Configuration - Tiamat (x86_64 Server)

timeout: 5
default_entry: 1

/NexusOS Tiamat
    protocol: limine
    path: boot():/boot/nexus-kernel
    cmdline: target=tiamat loglevel=info console=serial
