# NexusOS Limine Boot Configuration - Tiamat UEFI ISO
# kernel is in EFI/BOOT/ so it is accessible from boot() FAT image.

timeout: 5
default_entry: 1

/NexusOS Tiamat
    protocol: limine
    path: boot():/EFI/BOOT/nexus-kernel
    cmdline: target=tiamat loglevel=info console=serial
