http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.tiamat.local`)"
      entryPoints: [web]
      service: api@internal
    vaultwarden:
      rule: "Host(`vault.tiamat.local`) || Host(`vaultwarden.tiamat.local`)"
      entryPoints: [web]
      service: vaultwarden
    authentik:
      rule: "Host(`auth.tiamat.local`)"
      entryPoints: [web]
      service: authentik

  services:
    vaultwarden:
      loadBalancer:
        serversTransport: insecure-skip-verify@file
        servers:
          - url: "https://192.168.12.104:443"
    authentik:
      loadBalancer:
        servers:
          - url: "http://192.168.12.107:9000"

  serversTransports:
    insecure-skip-verify:
      insecureSkipVerify: true
