#!/bin/bash
# =============================================================================
# Passwordless SSH Setup — Tiamat Homelab
# Run this from the LAPTOP after Proxmox is installed and the Pi is up.
#
# What it does:
#   1. Pushes laptop public key to every system (Proxmox + Pi + containers)
#   2. Writes ~/.ssh/config with friendly host aliases
#   3. Generates a key ON Proxmox for root→containers (intra-host)
#
# Usage:
#   chmod +x scripts/setup-ssh-keys.sh
#   ./scripts/setup-ssh-keys.sh
#
# Re-run at any time — ssh-copy-id is idempotent.
# =============================================================================
set -e

PUBKEY="$HOME/.ssh/id_ed25519.pub"
PRIVKEY="$HOME/.ssh/id_ed25519"

# ── Hosts ────────────────────────────────────────────────────────────────────
PROXMOX_IP="192.168.12.242"
PI_IP="192.168.12.20"

# Containers (directly reachable on LAN once running)
CT_WG="192.168.12.100"
CT_PROXY="192.168.12.101"
CT_ADGUARD="192.168.12.102"
CT_MEDIA="192.168.12.110"
CT_FIRETV="192.168.12.150"

log()  { echo "[$(date '+%H:%M:%S')] $*"; }
ok()   { echo "  ✓ $*"; }
warn() { echo "  ⚠ $*"; }

# ── Check key ────────────────────────────────────────────────────────────────
if [ ! -f "$PUBKEY" ]; then
  log "No SSH key found — generating ed25519 key..."
  ssh-keygen -t ed25519 -C "loufogle@homelab-$(date +%Y%m%d)" -f "$PRIVKEY" -N ""
fi
PUBKEY_CONTENT=$(cat "$PUBKEY")
log "Using key: $PUBKEY_CONTENT"

# ── Helper: copy key with timeout ────────────────────────────────────────────
copy_key() {
  local user="$1" host="$2" label="$3"
  log "Copying key to $label ($user@$host)..."
  if ssh-copy-id -i "$PUBKEY" -o StrictHostKeyChecking=no \
       -o ConnectTimeout=8 "$user@$host" 2>/dev/null; then
    ok "$label"
  else
    warn "$label — unreachable or already done, skipping"
  fi
}

# ── 1. Proxmox host ──────────────────────────────────────────────────────────
log "=== Step 1: Proxmox host (tiamat @ $PROXMOX_IP) ==="
copy_key root "$PROXMOX_IP" "Tiamat (Proxmox)"

# ── 2. Ziggy (Raspberry Pi 3B+) ──────────────────────────────────────────────────────────
log "=== Step 2: Ziggy (Raspberry Pi 3B+) @ $PI_IP ==="
copy_key pi "$PI_IP" "Ziggy (Raspberry Pi 3B+)"

# ── 3. LXC Containers (direct LAN) ──────────────────────────────────────────
log "=== Step 3: LXC containers ==="
copy_key root "$CT_WG"     "CT-100 (WireGuard)"
copy_key root "$CT_PROXY"  "CT-101 (Gluetun proxy)"
copy_key root "$CT_ADGUARD" "CT-102 (AdGuard Home)"
copy_key root "$CT_MEDIA"  "CT-110 (Media Stack)"
copy_key root "$CT_FIRETV" "CT-150 (Fire TV Controller)"

# ── 4. Proxmox → containers intra-host key ──────────────────────────────────
log "=== Step 4: Generate Proxmox root key and push to containers ==="
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=8 "root@$PROXMOX_IP" bash <<'REMOTE'
set -e
# Generate key if not present
[ -f /root/.ssh/id_ed25519 ] || ssh-keygen -t ed25519 -C "root@tiamat" -f /root/.ssh/id_ed25519 -N ""
PROXMOX_PUB=$(cat /root/.ssh/id_ed25519.pub)

push_key() {
  local target="$1"
  ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 "root@$target" \
    "mkdir -p ~/.ssh && chmod 700 ~/.ssh && \
     grep -qF '$PROXMOX_PUB' ~/.ssh/authorized_keys 2>/dev/null || \
     echo '$PROXMOX_PUB' >> ~/.ssh/authorized_keys && \
     chmod 600 ~/.ssh/authorized_keys" 2>/dev/null && \
    echo "  ✓ $target" || echo "  ⚠ $target (not ready yet)"
}

push_key 192.168.12.100
push_key 192.168.12.101
push_key 192.168.12.102
push_key 192.168.12.110
push_key 192.168.12.150
REMOTE

# ── 5. Write ~/.ssh/config ───────────────────────────────────────────────────
log "=== Step 5: Writing ~/.ssh/config ==="

SSH_CONFIG="$HOME/.ssh/config"
MARKER="# ── Homelab Media Stack ──"

# Remove existing homelab block if present (idempotent)
if grep -q "$MARKER" "$SSH_CONFIG" 2>/dev/null; then
  log "Removing old homelab SSH config block..."
  awk "/$MARKER/{found=1} found && /^# ── END Homelab/{found=0; next} !found" \
    "$SSH_CONFIG" > /tmp/ssh_config_tmp && mv /tmp/ssh_config_tmp "$SSH_CONFIG"
fi

cat >> "$SSH_CONFIG" <<EOF

$MARKER
# Generated by setup-ssh-keys.sh — $(date)

Host tiamat
    HostName $PROXMOX_IP
    User root
    IdentityFile $PRIVKEY
    ServerAliveInterval 60
    ServerAliveCountMax 3

Host ziggy pi
    HostName $PI_IP
    User pi
    IdentityFile $PRIVKEY
    ServerAliveInterval 60

# Containers — direct LAN (no ProxyJump needed on same subnet)
Host ct-wg wg-server
    HostName $CT_WG
    User root
    IdentityFile $PRIVKEY

Host ct-proxy gluetun
    HostName $CT_PROXY
    User root
    IdentityFile $PRIVKEY

Host ct-adguard adguard
    HostName $CT_ADGUARD
    User root
    IdentityFile $PRIVKEY

Host ct-media media
    HostName $CT_MEDIA
    User root
    IdentityFile $PRIVKEY

Host ct-firetv firetv
    HostName $CT_FIRETV
    User root
    IdentityFile $PRIVKEY

# ── END Homelab ──
EOF

chmod 600 "$SSH_CONFIG"
ok "~/.ssh/config written"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "================================================="
echo "  Passwordless SSH Setup Complete"
echo "================================================="
echo ""
echo "Test connections:"
echo "  ssh tiamat          # Proxmox host"
echo "  ssh ziggy              # Ziggy (Raspberry Pi 3B+)"
echo "  ssh ct-media        # CT-110 media stack"
echo "  ssh ct-adguard      # CT-102 AdGuard Home"
echo "  ssh ct-wg           # CT-100 WireGuard server"
echo "  ssh ct-proxy        # CT-101 Gluetun proxy"
echo "  ssh ct-firetv       # CT-150 Fire TV controller"
echo ""
echo "Quick shortcuts:"
echo "  ssh tiamat 'pct list'                          # list containers"
echo "  ssh ct-media 'docker ps'                       # media stack status"
echo "  ssh tiamat 'pct exec 110 -- docker ps'         # alternative"
