#!/usr/bin/env bash
# Activision Launcher installer for PortProton
export PW_AUTOINSTALL_EXE="ActivisionLauncher_Setup.exe"
export PW_PREFIX_NAME="ACTIVISION_LAUNCHER"
export PW_VULKAN_USE="1"
PW_WINE_USE="PROTON_LG" try_download_installer \
"https://www.activision.com/" \
"$PW_AUTOINSTALL_EXE" \
"activision_launcher_installer"
