#!/usr/bin/env bash
# Discord installer for PortProton
export PW_AUTOINSTALL_EXE="DiscordSetup.exe"
export PW_PREFIX_NAME="DISCORD"
export PW_VULKAN_USE="1"
PW_WINE_USE="PROTON_LG" try_download_installer \
"https://discord.com/download" \
"$PW_AUTOINSTALL_EXE" \
"discord_installer"
