# NexusOS Calamares Bootloader Module Configuration
---
efiBootLoader: grub
kernel: /vmlinuz
img: /initrd.img
timeout: 10
grubInstall: grub-install
grubMkconfig: grub-mkconfig
grubCfg: /boot/grub/grub.cfg
grubProbe: grub-probe
efiBootloaderId: NexusOS
