# NexusOS Calamares fstab Module Configuration
---
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,compress=zstd:1,space_cache=v2
    ext4: defaults,noatime
    xfs: defaults,noatime

ssdExtraMountOptions:
    ext4: discard
    btrfs: discard=async
    xfs: discard

crypttabOptions: luks
