# NexusOS Calamares GRUB Configuration Module
---
distributor: NexusOS

keepDistributor: true

default: NexusOS

grubDefault: "0"

grubTimeout: 10

cmdlineLinuxDefault: "quiet splash plymouth.enable=1"
