# NexusOS Calamares Partition Module Configuration
---
efiSystemPartition: /boot/efi
efiSystemPartitionSize: 512M
efiSystemPartitionName: EFI

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true

defaultPartitionTableType: gpt

initialPartitioningChoice: erase
initialSwapChoice: small

defaultFileSystemType: ext4
availableFileSystemTypes:
    - ext4
    - btrfs
    - xfs
