# NexusOS Calamares Users Module Configuration
---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - sudo
    - docker
    - audio
    - video
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth

autologinGroup: autologin
doAutologin: false

sudoersGroup: sudo
sudoersConfigureWithGroup: false

setRootPassword: true
doReusePassword: true

passwordRequirements:
    minLength: 8
    maxLength: -1
    libpwquality: []

allowWeakPasswords: false
allowWeakPasswordsDefault: false

userShell: /bin/bash
setHostname: EtcFile
writeHostsFile: true
